### ISSUE TITLE
LFE use the increasing and decreasing structure 2-4-8-8-4-2

### ISSUE THREAD

**Issue by tangeroo** [konstantg/dem-fill#5]
@konstantg Hi,
   Sorry to bother again.I read the paper you referenced "Effective use of dilated convolutions for segmenting small object instances in remote sensing imagery".I noticed you used a different dialated structure 2-4-8-8-4-2 from the table below.Has it been a better choice for DEM?Did you have any test about this?
  Looking forward your reply.
  Thank you.
![image](https://user-images.githubusercontent.com/25971461/70105113-ef9bae80-167a-11ea-9c36-f1cf5be4f9c3.png)

**Comment by konstantg** [comment]
Hi @tangeroo ,

"Generative Image Inpainting with Contextual Attention" provides the main model we use for this work. They use a dilation structure of increasing dilation factors 2-4-8-16.

Taking note from "Effective use of dilated convolutions for segmenting small object instances in remote sensing imagery" we use a decreasing dilation factor module (Local Feature Extraction module or LFE) that _follows_ the increasing one (what they call a front-end module or FE).

Instead of 2-4-8-16 (increasing dilation) we use (2-4-8)-(8-4-2) or (FE)-(LFE).

This gave us better results compared to the just increasing one. We did not experiment further with different schemes for the LFE module (the table you provide) and just used the main idea of attaching a decreasing dilation factor structure in front of an increasing one. In practice, we use LFE-Dec from the table but with smaller depth and a larger factor for the first layer.

Hope this helps.

**Comment by tangeroo** [comment]
@konstantg ,thanks a lot, it really helps me understand more.
